### ISSUE TITLE
Front page 404 after content import

### ISSUE THREAD

**Issue by dreamwhisper** [maithemewp/mai-demo-importer#1]
After importing the content, the `View your website` button leads to the front page, but showed Page Not Found.

![notfound](https://user-images.githubusercontent.com/1271053/46824224-308d8100-cd5e-11e8-9c48-80191aceda56.png)

This is due to the Static Page being selected, but the Homepage and Pots Page not being set.

![static](https://user-images.githubusercontent.com/1271053/46824247-3f743380-cd5e-11e8-8ef6-a064ba4eac22.png)

**Comment by JiveDig** [comment]
Hey Jennifer. Did the Home and Blog/News pages actually get created and just not set, or we’re they never created?

**Comment by dreamwhisper** [comment]
@JiveDig They were created, but not set.

**Comment by JiveDig** [comment]
_Should_ be fixed in beta release.
