### ISSUE TITLE
Switching themes leads to wizard link

### ISSUE THREAD

**Issue by dreamwhisper** [maithemewp/mai-demo-importer#3]
Steps to replicate:
1) Activate Mai theme and install configurations plugin
2) Don't import content by using the wizard
3) Activate Genesis
4) There's a redirect to /wp-admin/themes.php?page=merlin which says `Sorry, you are not allowed to access this page.`

**Comment by JiveDig** [comment]
This is currently forced by MerlinWP but would be a nice addition to disable https://github.com/richtabor/MerlinWP/issues/133

**Comment by JiveDig** [comment]
This was fixed in the beta release.
